name: bwu_bind_html
version: 0.1.0
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: Add HTML to the DOM using Polymer mustache binding
homepage: https://github.com/bwu-dart/bwu_bind_html
environment:
  sdk: '>=1.8.2 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.6
  polymer_interop: ^1.0.0-rc.3
  reflectable: ^0.3.2
  web_components: ^0.12.0

dev_dependencies:
  bwu_grinder_tasks: '^0.1.0'
  grinder: '^0.8.0'
  test: ^0.12.5+1

transformers:
- web_components:
    entry_points:
    - test/bwu_bind_html_test.html
    - test/default_validator_test.html
- reflectable:
    entry_points:
    - test/bwu_bind_html_test.dart
    - test/default_validator_test.dart
- test/pub_serve:
    $include: test/**_test{.*,}.dart
#- $dart2js:
#    $include: '**/*.bootstrap.initialize.dart'
#    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']

